'use client'
import { CheckIcon, ArrowRightIcon, PlayIcon, SparklesIcon } from "lucide-react";
import TiltedImage from "../components/TiltImage";
import { motion } from "motion/react";
import { useNavigate } from "react-router-dom";

export default function HeroSection() {
    const navigate = useNavigate()
    const specialFeatures = [
        "No design skills needed",
        "Fast generation",
        "High CTR templates",
    ];

    return (
        <div className="relative flex flex-col items-center justify-center px-4 md:px-16 lg:px-24 xl:px-32 overflow-hidden">
            {/* background grid + glow */}
            <div className="absolute inset-0 -z-20 bg-[linear-gradient(to_right,#1e293b_1px,transparent_1px),linear-gradient(to_bottom,#1e293b_1px,transparent_1px)] bg-[size:48px_48px] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_60%,transparent_100%)]"></div>
            <div className="absolute top-0 -z-10 left-1/2 -translate-x-1/2 w-[500px] h-[500px] bg-blue-600/25 blur-[160px] rounded-full"></div>

            <motion.div className="mt-40 flex items-center gap-2 rounded-full px-4 py-1.5 border border-blue-800 bg-blue-950/40 text-sm text-blue-300"
                initial={{ y: -20, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                viewport={{ once: true }}
                transition={{ delay: 0.2, type: "spring", stiffness: 320, damping: 70, mass: 1 }}
            >
                <SparklesIcon size={14} />
                <span>Your first thumbnail is on the house</span>
            </motion.div>

            <motion.h1 className="mt-6 text-4xl sm:text-5xl md:text-6xl font-semibold max-w-3xl text-center leading-tight text-white"
                initial={{ y: 50, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                viewport={{ once: true }}
                transition={{ type: "spring", stiffness: 240, damping: 70, mass: 1 }}
            >
                Thumbnails that get the click,{" "}
                <span className="text-blue-500">generated by AI</span>
            </motion.h1>

            <motion.p className="text-base md:text-lg text-center text-slate-400 max-w-xl mt-5"
                initial={{ y: 50, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                viewport={{ once: true }}
                transition={{ delay: 0.2, type: "spring", stiffness: 320, damping: 70, mass: 1 }}
            >
                Skip the design grind. Describe your video, pick a style, and get a scroll-stopping thumbnail in seconds.
            </motion.p>

            <motion.div className="flex flex-col sm:flex-row items-center gap-3 mt-8 w-full sm:w-auto"
                initial={{ y: 50, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                viewport={{ once: true }}
                transition={{ type: "spring", stiffness: 320, damping: 70, mass: 1 }}
            >
                <button onClick={()=> navigate('/generate')} className="group w-full sm:w-auto flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-500 text-white font-medium rounded-lg px-7 h-12 transition-colors">
                    Generate Now
                    <ArrowRightIcon size={16} className="group-hover:translate-x-1 transition-transform" />
                </button>
                <button className="w-full sm:w-auto flex items-center justify-center gap-2 bg-white/5 hover:bg-white/10 border border-white/10 text-slate-200 rounded-lg px-6 h-12 transition-colors">
                    <PlayIcon size={16} />
                    <span>See how it works</span>
                </button>
            </motion.div>

            <div className="flex flex-wrap justify-center items-center gap-x-8 gap-y-3 mt-10 pb-6">
                {specialFeatures.map((feature, index) => (
                    <motion.p className="flex items-center gap-2 text-sm" key={index}
                        initial={{ y: 20, opacity: 0 }}
                        whileInView={{ y: 0, opacity: 1 }}
                        viewport={{ once: true }}
                        transition={{ delay: index * 0.15, duration: 0.3 }}
                    >
                        <span className="flex items-center justify-center size-4 rounded-full bg-blue-500/20">
                            <CheckIcon className="size-2.5 text-blue-400" strokeWidth={3} />
                        </span>
                        <span className="text-slate-400">{feature}</span>
                    </motion.p>
                ))}
            </div>

            <div className="relative w-full max-w-4xl">
                <div className="absolute -inset-x-10 -inset-y-6 -z-10 bg-blue-600/10 blur-3xl rounded-full"></div>
                <TiltedImage />
            </div>
        </div>
    );
}